import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AOSInit } from "@/utils/aos";

import { Paytone_One,Roboto } from 'next/font/google'
 
// const Paytone_OneFont = Paytone_One({
// 	  weight: "400",
// 	  display: 'swap',
// 	  subsets: ['latin'],
// })

const RobotoFont = Roboto({
	  weight: "400",
	  display: 'swap',
	  subsets: ['latin'],
})



export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { FloatingNav } from "@/components/NavBar";
import Footer from "@/components/Footer";
const navItems = [
	{
		name: "Home",
		link: "/",
	},
	{
		name: "Portfolio",
		link: "/portfolio",
	},
	{
		name: "Services",
		link: "/services",
	},
	{
		name: "Resume",
		link: "/resume",
	},
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AOSInit />
			
			

			<body
				className={RobotoFont.className}
				
			>
				<FloatingNav navItems={navItems} />
				{children}
				<Footer />
			</body>
		</html>
	);
}
